name: Run PHP Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # تشغيل كل 5 دقائق
  workflow_dispatch: # إمكانية تشغيله يدويًا من Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run PHP Script
        run: php os.php
