name: Run Multiple Scripts

on:
  schedule:
    - cron: '*/5 * * * *'  # تشغيل كل 5 دقائق
  workflow_dispatch:

jobs:
  script1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Script 1
        run: php os.php

  script2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Script 2
        run: php auto_renew.php
